In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
a=np.zeros([2,2],dtype=int)
print(a)

[[0 0]
 [0 0]]


In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(a,b)
print(c)

[5 7 9]


In [5]:
a=np.arange(10,1,-2)
print(a)
newarr=a[np.array([3,1,2])]
print(newarr)

[10  8  6  4  2]
[4 8 6]


In [ ]:
import numpy as np

a = np.arange(20)
print("\n Array is:\n ",a)

print("\n a[-8:17:1] = ",a[-8:17:1])

print("\n a[10:] = ",a[10:])

In [ ]:
import numpy as np

macros = np.array([
    [0.8, 2.9, 3.9],
    [52.4, 23.6, 36.5],
    [55.2, 31.7, 23.9],
    [14.4, 11, 4.9]
])

cal_per_macro = np.array([3, 3, 8])

result = macros * cal_per_macro

print(result)

In [ ]:
import numpy as np

v = np.array([12, 24, 36])
w = np.array([45, 55])

print(np.reshape(v, (3, 1)) * w)
X = np.array([[12, 22, 33], [45, 55, 66]])
print(X + v)
print((X.T + w).T)
print(X * 2)


In [8]:
a=np.random.seed(0)
print(a)
b=np.random.rand(3,4)
print(b)

None
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]]


In [ ]:
a=np.reshape(np.arange(12),(3,4))
print(a)
# Difference: arr.reshape() vs arr.resize()
# reshape: returns a new reshaped array
# resize: changes the original array


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [11]:
a=np.array([1,22,33,44,55,66,77,88,99])
b=np.unique(a)
print(b)

[ 1 22 33 44 55 66 77 88 99]


In [12]:
import numpy as np

print("\n1. Create NumPy array")
arr = np.array([1, 2, 3, 4, 5])
print(arr)

print("\n2. Arrays of zeros, ones, random")
zeros = np.zeros(5)
ones = np.ones((2, 3))
rand = np.random.rand(3, 3)
print(zeros, "\n", ones, "\n", rand)

print("\n3. Reshape array")
reshaped = np.arange(1, 7).reshape(2, 3)
print(reshaped)

print("\n4. Shape, ndim, size")
print(arr.shape, arr.ndim, arr.size)

print("\n5. Range of numbers")
range_arr = np.arange(1, 10, 2)
lin_arr = np.linspace(0, 1, 5)
print(range_arr, "\n", lin_arr)

print("\n6. Basic stats")
nums = np.array([10, 20, 30, 40, 50])
print(nums.max(), nums.min(), nums.sum(), nums.mean())

print("\n7. Std and Variance")
print(nums.std(), nums.var())

print("\n8. Slicing")
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0:2, 1:3])

print("\n9. Boolean Indexing")
even_nums = nums[nums % 2 == 0]
print(even_nums)

print("\n10. Horizontal & Vertical stack")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.hstack((a, b)))
print(np.vstack((a, b)))

print("\n11. Vectorized operations")
print(arr + 5)
print(arr * 10)

print("\n12. Matrix multiplication")
mat1 = np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])
print(np.dot(mat1, mat2))

print("\n13. Unique values")
dup_arr = np.array([1, 2, 2, 3, 4, 4, 5])
print(np.unique(dup_arr))

print("\n14. Flatten array")
print(mat.flatten())

print("\n15. Python list → NumPy array")
py_list = [10, 20, 30]
print(np.array(py_list))

print("\n16. Check data type")
print(arr.dtype)

print("\n17. Change data type")
print(arr.astype(float))

print("\n18. Percentiles")
print(np.percentile(nums, 75))

print("\n19. Correlation")
x = np.array([1,2,3,4,5])
y = np.array([2,4,6,8,10])
print(np.corrcoef(x, y))

print("\n20. Identity matrix")
print(np.eye(5))

print("\n21. Replace negative values with 0")
neg = np.array([1, -5, 3, -2, 7])
neg[neg < 0] = 0
print(neg)

print("\n22. Normalize array (0-1 scale)")
norm = (nums - nums.min()) / (nums.max() - nums.min())
print(norm)

print("\n23. Reshape vs Resize")
r1 = np.arange(6)
print("reshape:", r1.reshape(2,3))
r2 = np.arange(6)
r2.resize(3,2)
print("resize:", r2)

print("\n24. Create 2D random int matrix")
print(np.random.randint(1, 100, size=(4, 4)))

print("\n25. Delete a row or column")
sample = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Delete row 1:", np.delete(sample, 1, axis=0))
print("Delete col 2:", np.delete(sample, 2, axis=1))



1. Create NumPy array
[1 2 3 4 5]

2. Arrays of zeros, ones, random
[0. 0. 0. 0. 0.] 
 [[1. 1. 1.]
 [1. 1. 1.]] 
 [[0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]
 [0.77815675 0.87001215 0.97861834]]

3. Reshape array
[[1 2 3]
 [4 5 6]]

4. Shape, ndim, size
(5,) 1 5

5. Range of numbers
[1 3 5 7 9] 
 [0.   0.25 0.5  0.75 1.  ]

6. Basic stats
50 10 150 30.0

7. Std and Variance
14.142135623730951 200.0

8. Slicing
[[2 3]
 [5 6]]

9. Boolean Indexing
[10 20 30 40 50]

10. Horizontal & Vertical stack
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]

11. Vectorized operations
[ 6  7  8  9 10]
[10 20 30 40 50]

12. Matrix multiplication
[[19 22]
 [43 50]]

13. Unique values
[1 2 3 4 5]

14. Flatten array
[1 2 3 4 5 6 7 8 9]

15. Python list → NumPy array
[10 20 30]

16. Check data type
int64

17. Change data type
[1. 2. 3. 4. 5.]

18. Percentiles
40.0

19. Correlation
[[1. 1.]
 [1. 1.]]

20. Identity matrix
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [

In [13]:
import pandas as pd

df = pd.DataFrame()
print(df)

lst = ['Geeks', 'For', 'Geeks', 'is', 'portal', 'for', 'Geeks']

df = pd.DataFrame(lst, columns=['Words'])

print(df)

Empty DataFrame
Columns: []
Index: []
    Words
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks


In [14]:
df=pd.read_csv('Iris.csv')
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
import pandas as pd

df = pd.read_csv("Iris.csv")

df.filter(["Species", "SepalLengthCm", "SepalLengthCm"]).head()

Species  SepalLengthCm
0  Iris-setosa            5.1
1  Iris-setosa            4.9
2  Iris-setosa            4.7
3  Iris-setosa            4.6
4  Iris-setosa            5.0